### ISSUE TITLE
README.md file needs update

### ISSUE THREAD

**Issue by adriatic** [zewa666/aurelia-store-examples#1]
The **[Usage section](https://github.com/zewa666/aurelia-store-examples#usage)** states:
> - Navigate to a samples subfolder in your command line

There is no **samples** subfolder

You most have used the term **samples** as the generic reference to **`contacts`**, **`electron`**, etc

**Comment by zewa666** [comment]
Exactly, what would you propose instead?

**Comment by adriatic** [comment]
Navigate to any subfolder from the set of [`contacts`, `electron`, `immer`, `markdown`, `services`, `todo`, `vis`]

**Comment by zewa666** [comment]
Done
