### ISSUE TITLE
Code formatting that makes eslint happy

### ISSUE THREAD

**Issue by adriatic** [zewa666/aurelia-store-examples#4]
Here the screenshot of the original source code:

![image](https://user-images.githubusercontent.com/2712405/36643976-399c0370-1a21-11e8-8b80-801657365f31.png)
![image](https://user-images.githubusercontent.com/2712405/36643981-4da655a0-1a21-11e8-89a6-90afb7791289.png)

Since eslint is enabled, the only action needed to fix it is to ask the editor to reformat the code:

![image](https://user-images.githubusercontent.com/2712405/36644004-ab4644c2-1a21-11e8-9db3-1e812470baef.png)

I suggest to do this with all aurelia-store samples before releasing them

**Comment by adriatic** [comment]
Unless you ask me to, I believe that it is better that you do the reformatting to the eslint satisfaction than making a bunch of PRs for that.

**Comment by zewa666** [comment]
Will do so, just copied the Initial state of the original contacts app which already has those misformatting.

**Comment by adriatic** [comment]
Yes, there were only few such files in the whole collection.
