### ISSUE TITLE
todo example state mutation

### ISSUE THREAD

**Issue by lj1000** [zewa666/aurelia-store-examples#6]
in the todo example in mutations.js is the state seems to be getting mutated. 
e.g 

function completeTodo(state, todo) {
  todo.isComplete = !todo.isComplete;

  return updateTodoCollection(state, todo);
}

should it not be 

function completeTodo(state, todo) {
  const newTodo = Object.assign({}, todo);
  newTodo.isComplete = !newTodo.isComplete;

  return updateTodoCollection(state, newTodo);
}

**Comment by zewa666** [comment]
Ouch super oversight ;) thx for pointing that out

**Comment by lj1000** [comment]
editTodo and activateTodoEditMode are similar too.

great example by the way. nice and clear. thanks for the hard work.

**Comment by zewa666** [comment]
Ok I've updated the sample and also updated the dependencies. Now interaction with the Redux Devtools should also work properly.
